# Generated by Django 5.2 on 2026-07-25 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='رقم الحجز')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكد'), ('checked_in', 'تم الدخول'), ('checked_out', 'تم الخروج'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='confirmed', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('walk_in', 'حضور مباشر'), ('phone', 'هاتف'), ('online', 'الموقع الإلكتروني'), ('ota', 'قناة خارجية')], default='walk_in', max_length=20, verbose_name='مصدر الحجز')),
                ('check_in', models.DateField(verbose_name='تاريخ الدخول')),
                ('check_out', models.DateField(verbose_name='تاريخ الخروج')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='البالغون')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='الأطفال')),
                ('actual_check_in', models.DateTimeField(blank=True, null=True, verbose_name='دخول فعلي')),
                ('actual_check_out', models.DateTimeField(blank=True, null=True, verbose_name='خروج فعلي')),
                ('special_requests', models.TextField(blank=True, verbose_name='طلبات خاصة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الليلة')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_rooms', to='hotels.room')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'غرفة الحجز',
                'verbose_name_plural': 'غرف الحجز',
            },
        ),
    ]
