# Generated by Django 5.2 on 2026-07-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtypephoto'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='reservations.reservation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.service')),
            ],
            options={
                'verbose_name': 'خدمة الحجز',
                'verbose_name_plural': 'خدمات الحجز',
            },
        ),
    ]
