# Generated by Django 5.2 on 2026-07-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_company'),
        ('reservations', '0002_reservationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='guests.company', verbose_name='شركة/وكيل'),
        ),
    ]
