# Generated by Django 5.2 on 2026-07-25 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_company'),
        ('hotels', '0003_roomtypephoto'),
        ('reservations', '0003_reservation_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('transfer', 'تحويل'), ('online', 'دفع إلكتروني')], default='cash', max_length=10, verbose_name='الطريقة')),
                ('reference', models.CharField(blank=True, max_length=60, verbose_name='مرجع')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='مُسترد')),
                ('applied', models.BooleanField(default=False, verbose_name='طُبّق على الفاتورة')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'عربون',
                'verbose_name_plural': 'العرابين',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المجموعة')),
                ('check_in', models.DateField(verbose_name='الوصول')),
                ('check_out', models.DateField(verbose_name='المغادرة')),
                ('status', models.CharField(choices=[('tentative', 'مبدئي'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='tentative', max_length=12, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='guests.company', verbose_name='شركة/وكيل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'بلوك مجموعة',
                'verbose_name_plural': 'بلوكات المجموعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='العدد')),
                ('rate_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الليلة')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.roomtype')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_rooms', to='reservations.groupblock')),
            ],
            options={
                'verbose_name': 'غرف البلوك',
                'verbose_name_plural': 'غرف البلوكات',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.groupblock', verbose_name='بلوك مجموعة'),
        ),
    ]
