# Generated by Django 5.2 on 2026-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_deposit_groupblock_blockroom_reservation_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('cheque', 'شيك'), ('transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني')], default='cash', max_length=10, verbose_name='الطريقة'),
        ),
    ]
