# Generated by Django 5.2 on 2026-07-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge_reason_transactioncode_and_more'),
        ('reservations', '0005_alter_deposit_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('once', 'مرة واحدة')], default='daily', max_length=10, verbose_name='التكرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_posted', models.DateField(blank=True, null=True, verbose_name='آخر ترحيل')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_charges', to='reservations.reservation')),
                ('transaction_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.transactioncode')),
            ],
            options={
                'verbose_name': 'رسم ثابت',
                'verbose_name_plural': 'الرسوم الثابتة',
            },
        ),
    ]
