# Generated by Django 5.2 on 2026-07-25 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_fixedcharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alert', 'تنبيه'), ('trace', 'أثر (مهمة قسم)')], default='alert', max_length=8, verbose_name='النوع')),
                ('message', models.CharField(max_length=255, verbose_name='الرسالة')),
                ('department', models.CharField(blank=True, max_length=60, verbose_name='القسم')),
                ('show_on_checkin', models.BooleanField(default=True, verbose_name='يظهر عند الدخول')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='منجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'تنبيه حجز',
                'verbose_name_plural': 'تنبيهات الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
