# Generated by Django 5.2 on 2026-07-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('hotels', '0002_housekeepingtask_maintenancerequest_seasonalrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('kind', models.CharField(choices=[('percent', 'نسبة %'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='النوع')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='صالح من')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = بلا حد', verbose_name='أقصى استخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='فارغ = كل الفنادق', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
    ]
