# Generated by Django 5.2 on 2026-07-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_coupon'),
        ('guests', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='window',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='النافذة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_invoices', to='guests.company', verbose_name='على حساب شركة'),
        ),
    ]
