# Generated by Django 5.2 on 2026-07-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_charge_window_invoice_bill_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('cheque', 'شيك'), ('transfer', 'تحويل بنكي'), ('online', 'دفع إلكتروني'), ('city_ledger', 'حساب آجل (شركة)'), ('wallet', 'محفظة رقمية')], default='cash', max_length=15, verbose_name='طريقة الدفع'),
        ),
    ]
