# Generated by Django 5.2 on 2026-07-25 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_method'),
        ('hotels', '0004_room_hk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='سبب التسوية'),
        ),
        migrations.CreateModel(
            name='TransactionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (EN)')),
                ('category', models.CharField(choices=[('room', 'إقامة'), ('fnb', 'مأكولات ومشروبات'), ('service', 'خدمات'), ('tax', 'ضرائب'), ('other', 'أخرى')], default='other', max_length=10, verbose_name='التصنيف')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hotel', models.ForeignKey(blank=True, help_text='فارغ = كل الفنادق', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_codes', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'كود بند',
                'verbose_name_plural': 'أكواد البنود',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='transaction_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.transactioncode', verbose_name='كود البند'),
        ),
    ]
