# Generated by Django 5.2 on 2026-07-25 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=80, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='الاسم (EN)')),
            ],
            options={
                'verbose_name': 'بند مصروف',
                'verbose_name_plural': 'بنود المصروفات',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='على رأس العمل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('vendor', models.CharField(blank=True, max_length=120, verbose_name='المورد')),
                ('paid_at', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hotels.hotel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='بدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصومات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='finance.employee')),
            ],
            options={
                'verbose_name': 'راتب',
                'verbose_name_plural': 'الرواتب',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='رصيد الافتتاح')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='رصيد الإغلاق')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الفتح')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوحة')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'ordering': ['-opened_at'],
            },
        ),
    ]
