# Generated by Django 5.2 on 2026-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='اسم العائلة')),
                ('id_type', models.CharField(choices=[('national_id', 'هوية وطنية'), ('iqama', 'إقامة'), ('passport', 'جواز سفر')], default='national_id', max_length=20, verbose_name='نوع الهوية')),
                ('id_number', models.CharField(db_index=True, max_length=40, verbose_name='رقم الهوية/الجواز')),
                ('nationality', models.CharField(default='السعودية', max_length=60, verbose_name='الجنسية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='قائمة سوداء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='guest_ids/', verbose_name='صورة الهوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نزيل',
                'verbose_name_plural': 'النزلاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
