# Generated by Django 5.2 on 2026-07-25 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'هوية وطنية'), ('iqama', 'إقامة'), ('passport', 'جواز سفر عادي'), ('passport_diplomatic', 'جواز سفر دبلوماسي'), ('passport_mission', 'جواز سفر مهام')], default='national_id', max_length=20, verbose_name='نوع الهوية'),
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('id', 'هوية/إقامة'), ('passport', 'جواز سفر'), ('visa', 'تأشيرة'), ('other', 'أخرى')], default='id', max_length=12, verbose_name='النوع')),
                ('file', models.FileField(upload_to='guest_docs/', verbose_name='الملف')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='ملاحظة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guests.guest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مستند عميل',
                'verbose_name_plural': 'مستندات العملاء',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
