# Generated by Django 5.2 on 2026-07-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_id_type_guestdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('company', 'شركة'), ('travel_agent', 'وكيل سياحة')], default='company', max_length=15, verbose_name='النوع')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='مسؤول التواصل')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=40, verbose_name='الرقم الضريبي')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حد الائتمان')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='خصم متفق %')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='عمولة الوكيل %')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, verbose_name='مدة السداد (يوم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شركة/وكيل',
                'verbose_name_plural': 'الشركات ووكلاء السياحة',
                'ordering': ['name'],
            },
        ),
    ]
