# Generated by Django 5.2 on 2026-07-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=80, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='الاسم (EN)')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرافق',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=120, verbose_name='الاسم بالإنجليزي')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='الرقم الضريبي')),
                ('star_rating', models.PositiveSmallIntegerField(default=4, verbose_name='التصنيف (نجوم)')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='موعد الدخول')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='موعد الخروج')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='الشعار')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فندق',
                'verbose_name_plural': 'الفنادق',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='رقم الطابق')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='الاسم')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'طابق',
                'verbose_name_plural': 'الطوابق',
                'unique_together': {('hotel', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (EN)')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='الكود')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الأساسي/ليلة')),
                ('max_adults', models.PositiveSmallIntegerField(default=2, verbose_name='عدد البالغين')),
                ('max_children', models.PositiveSmallIntegerField(default=1, verbose_name='عدد الأطفال')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room_types/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='hotels.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'نوع غرفة',
                'verbose_name_plural': 'أنواع الغرف',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الغرفة')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('reserved', 'محجوزة'), ('cleaning', 'قيد التنظيف'), ('maintenance', 'صيانة'), ('blocked', 'موقوفة')], default='available', max_length=20, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotels.floor')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'ordering': ['hotel', 'number'],
                'unique_together': {('hotel', 'number')},
            },
        ),
    ]
