# Generated by Django 5.2 on 2026-07-25 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cleaning', 'تنظيف'), ('deep_clean', 'تنظيف شامل'), ('laundry', 'غسيل ومفروشات'), ('inspection', 'تفتيش')], default='cleaning', max_length=15, verbose_name='النوع')),
                ('status', models.CharField(choices=[('pending', 'معلّقة'), ('in_progress', 'جارية'), ('done', 'منجزة')], default='pending', max_length=15, verbose_name='الحالة')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنجاز')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housekeeping_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المكلّف')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotels.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotels.room')),
            ],
            options={
                'verbose_name': 'مهمة تدبير',
                'verbose_name_plural': 'مهام التدبير الفندقي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العطل')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'جاري الإصلاح'), ('resolved', 'تم الإصلاح')], default='open', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإصلاح')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hotels.hotel')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='hotels.room')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموسم')),
                ('start_date', models.DateField(verbose_name='من')),
                ('end_date', models.DateField(verbose_name='إلى')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الليلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'سعر موسمي',
                'verbose_name_plural': 'الأسعار الموسمية',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم (EN)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات الإضافية',
            },
        ),
    ]
