# Generated by Django 5.2 on 2026-07-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_housekeepingtask_maintenancerequest_seasonalrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='وصف')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'صورة غرفة',
                'verbose_name_plural': 'صور الغرف',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
