# Generated by Django 5.2 on 2026-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomtypephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hk_status',
            field=models.CharField(choices=[('clean', 'نظيفة'), ('dirty', 'متسخة'), ('inspected', 'مفحوصة'), ('out_of_order', 'خارج الخدمة')], default='clean', max_length=15, verbose_name='حالة التدبير'),
        ),
    ]
