# Generated by Django 5.2 on 2026-07-25 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0003_roomtypephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(verbose_name='تاريخ اليوم')),
                ('total_rooms', models.PositiveIntegerField(default=0, verbose_name='إجمالي الغرف')),
                ('rooms_sold', models.PositiveIntegerField(default=0, verbose_name='غرف مباعة')),
                ('occupancy', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الإشغال %')),
                ('adr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='متوسط سعر الغرفة')),
                ('revpar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإيراد لكل غرفة')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إيراد اليوم')),
                ('arrivals', models.PositiveIntegerField(default=0, verbose_name='الوصول')),
                ('departures', models.PositiveIntegerField(default=0, verbose_name='المغادرات')),
                ('no_shows', models.PositiveIntegerField(default=0, verbose_name='لم يحضروا')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='فارغ = كل الفنادق', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night_audits', to='hotels.hotel')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تدقيق ليلي',
                'verbose_name_plural': 'التدقيق الليلي',
                'ordering': ['-business_date', '-run_at'],
            },
        ),
    ]
