# Generated by Django 5.2 on 2026-07-25 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=80, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='الاسم (EN)')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_categories', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='رقم الطلب')),
                ('order_type', models.CharField(choices=[('dine_in', 'محلي'), ('takeaway', 'سفري'), ('room_service', 'خدمة الغرف')], default='dine_in', max_length=15, verbose_name='النوع')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('paid', 'مدفوع'), ('room_charged', 'محمّل على الغرفة'), ('void', 'ملغي')], default='open', max_length=15, verbose_name='الحالة')),
                ('table_no', models.CharField(blank=True, max_length=10, verbose_name='رقم الطاولة')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='الضريبة %')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to='hotels.hotel')),
                ('reservation', models.ForeignKey(blank=True, help_text='عند التحميل على غرفة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'طلبات نقطة البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (EN)')),
                ('sku', models.CharField(blank=True, max_length=40, verbose_name='الباركود/الكود')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pos/', verbose_name='صورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pos.category')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_products', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الأصناف',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='ملاحظة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
            ],
            options={
                'verbose_name': 'بند طلب',
                'verbose_name_plural': 'بنود الطلب',
            },
        ),
    ]
